### PR TITLE
in dark mode, label will be more visible

### LINKED ISSUE #61: label of setting input field not visible
**Describe the bug**
When in dark mode. The label of text field(input field) in setting page are not quite visible. The colour of label is black in dark background, for which it is hard to see the input.

**To Reproduce**

1. Toggle dark mode
2. Go to setting page
3. collapse Bandwidth (or any)
4. below sub heading (Transfer rate throttle or any )
5. The label is black in dark background, less visibility (Global download rate throttle)

**Expected behavior**
The label should be white in dark background (dark mode)

**Screenshots**
Simulator Screen Shot - iPhone 13 - 2022-02-01 at 12 14 04

**Device Information [optional]:**

- OS: iOS simulator 

**Additional context**

**Are you working on this issue? (Yes/No)**
yes

### PR DESCRIPTION
**Pull request by raysummee**
Fixes #61 

Describe the changes you have made in this PR -

When user toggle to dark mode, the label in setting input field will be more visible (white54 instead of shadow black in dark mode. in light mode shadow black will be shown as before)

Screenshots of the changes (If any) -

Before:
Simulator Screen Shot - iPhone 13 - 2022-02-01 at 12 14 04

After:
Simulator Screen Shot - iPhone 13 - 2022-02-01 at 12 47 31

### CODE REVIEW

File: lib/Components/settings_text_field.dart [hunk 1]
```diff
@@ -29,7 +29,7 @@ class _SettingsTextFieldState extends State<SettingsTextField> {
         Text(
           widget.labelText,
           style: TextStyle(
-            color: ThemeProvider.theme.shadowColor,
+            color: ThemeProvider().isDarkMode? Colors.white54:ThemeProvider.theme.shadowColor,
```
Comment (pratikbaid3) [inline lib/Components/settings_text_field.dart:32]: @raysummee A better way will be to have another color defined in the theme. Maybe a textAcentColor that is white54 in dark theme and black/grey in light theme. 

Having all the color related info in the theme will help us maintain a single source of information.

Comment (raysummee) [reply lib/Components/settings_text_field.dart:32]: Sure. I'll do that then. 😊

Comment (raysummee) [reply lib/Components/settings_text_field.dart]: @pratikbaid3 I used unselectedWidgetColor theme colour. Which is giving me the required colour inbuilt. Please check the latest commit. 

screenshots:
Simulator Screen Shot - iPhone 13 - 2022-02-02 at 13 17 07 Simulator Screen Shot - iPhone 13 - 2022-02-02 at 13 17 09

**Comment by raysummee** [comment]
@pratikbaid3 I used unselectedWidgetColor theme colour. Which is giving me the required colour inbuilt. Please check the latest commit.

**Comment by pratikbaid3** [comment]
@raysummee Thank you for the contirbution
